### PR TITLE
Replace transformer with basic string replacer

### PR DESCRIPTION
**Pull request by User9684**

### CODE REVIEW

**Comment by User9684** [comment]
there wasn't a reopen button

**Comment by User9684** [comment]
Don't merge, just realized that characters that have the diacritic built into it aren't changed

**Comment by User9684** [comment]
> Don't merge, just realized that characters that have the diacritic built into it aren't changed

As far as I have seen, this was fixed and meets unicode specification

**Comment by ashishjh-bst** [comment]
You'll have to explain in detail what all changes you're doing here, because your code doesn't make it obvious, I see that you're making a go file, but it doesn't explain for what?

**Pull request merged**
