### PR TITLE
Publish message feed support

### PR DESCRIPTION
**Pull request by SoggySaussages**
This PR adds full support for YouTube and Streaming feeds to be published, either with a toggle or with `publishResponse`. This is an improvement over the current workaround where a user needs to `sendMessageRetID` and subsequently `publishMessage`. Using the toggle should work regardless of using custom or builtin message, and the toggle makes it clearer to users that the function is supported.

In addition, this pr merges three `IsExecedBy...` bool fields from template context into a single `ExecutedFrom` field.

### CODE REVIEW

**Comment by ashishjh-bst** [comment]
Can you  add a screenshot of the UI please?

**Comment by SoggySaussages** [comment]
Please see attached:
Screenshot 2023-10-04 at 23 04 39
Screenshot 2023-10-04 at 23 04 26
Screenshot 2023-10-04 at 23 04 14

**Comment by ashishjh-bst** [comment]
I don't think this needs a dedicated toggle, and should be done by custom notification template using publishMessage or publishResponse.

**Comment by SoggySaussages** [comment]
Cool, I've removed the toggle now

**Pull request merged**
