### PR TITLE
modified inspire.go

### PR DESCRIPTION
**Pull request by Shadow21AR**
😭 finally ....
Modified the inspire.go to have text paginated output.

### CODE REVIEW

**Comment by ashishjh-bst** [comment]
Please add screenshots of the modifications made and example command usage.

**Comment by Shadow21AR** [comment]
<details>
<summary>Screenshot of the modifications made and example command usage.</summary>

<br>
</details>
Modification : added optional "mindfulness" arg that can generate text output

**Review by Shadow21AR — COMMENTED** [review]
change mindful arg to mildfulness flag in inputs

**Comment by Shadow21AR** [comment]
image
Use of modification

**Pull request merged**
