### PR TITLE
Update: bottom margin added in redeem code input box

### PR DESCRIPTION
**Pull request by golu7679**
This PR is regarding to improve UI of website. 

Before:
image

After: 
image

### CODE REVIEW

**Comment by golu7679** [comment]
Input box and buttons are too closed, just want to add some spaces to make better, it is not necessary. If you want I can close this PR.

**Comment by l-zeuch** [comment]
> Input box and buttons are too closed [sic], just want to add some
> spaces to make it better.

So why haven't you included that in your description? That would have
been very much necessary information on why this patch should be merged.

Not having a description is a fairly simple way to not get your patch
accepted. It's like your mathematics teacher writing something on the
board and stating "this is all fairly trivial", while, in fact, it is
very much not trivial and you and your classmates are more confused than
an American at a salad bar.

> If you want I can close this PR.

Where did I say "you should close this PR"? You raised this pull request
against the wrong branch, as pointed out by our contributing guidelines.

If you need help with selecting the base branch and thus editing your
pull request to be against said base branch, you should consult GitHub's
documentation, mainly this page:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by golu7679** [comment]
@l-zeuch Thank you bro for your guide. I am adding the other stuffs in this PR.

**Comment by User9684** [comment]
That's better.

**Pull request merged**
