### PR TITLE
Fix calc dependency to include a correct implementation of acot

### PR DESCRIPTION
**Pull request by ei14**
One dependency is changed: from alfredxing/calc to ei14/calc.

Compared to alfredxing/calc, ei14/calc is different by 1 line.

Prior to this fix, `-c acot(0)` returns 90 despite the fact that every other trig function is in radians. Furthermore, `-c acot(1e100)` returns 90 - pi/2 instead of a near-zero value as it should. These discrepancies are caused by `acot` being calculated as `90 - atan` instead of `pi/2 - atan`.

ei14/calc has a correct implementation of `acot`.

### CODE REVIEW

**Comment by ashishjh-bst** [comment]
You should rather raise a PR to github.com/alfredxing/calc for this.

**Comment by l-zeuch** [comment]
[alfredxing/calc](https://github.com/alfredxing/calc) is archived by the author and thus does not accept any pull requests and the like.

Updating the dependency to a maintained fork is the ideal way of getting correct behaviour.

**Comment by ashishjh-bst** [comment]
Oh okay, I'll in that case switch to this fork then. Thanks @l-zeuch

**Comment by jo3-l** [comment]
Unless I'm mistaken, this PR breaks the build. I'm getting several errors along the lines of `no required module provides package github.com/alfredxing/calc/constants` with this commit. It seems like this issue was fixed in https://github.com/ei14/calc/commit/adbe43bdf8019134486df43b1f2a807dd63a3e34, but the version in go.mod points to the previous commit.

**Comment by ashishjh-bst** [comment]
> Unless I'm mistaken, this PR breaks the build; I'm getting several errors along the lines of `no required module provides package github.com/alfredxing/calc/constants` with this commit. It seems like this issue was fixed in [ei14/calc@adbe43b](https://github.com/ei14/calc/commit/adbe43bdf8019134486df43b1f2a807dd63a3e34), but the version in go.mod points to the previous commit.

@jo3-l  fixed in #1168

**Comment by SeniorMars** [comment]
Thank you for this fix. This has made the bot way better.

**Pull request merged**
