### PR TITLE
fix: Clean-up usage of X-Audit-Log-Reason

### PR DESCRIPTION
**Pull request by Wolveric**
It was recently noted that the YAGPDB was not setting an audit log reason, when kicking users via command, or when unbanning users. This first of these, was due to the fact the relevant method was based on an old API design, and hadn't been updated, and the second because the relevant method didn't exist.

This PR fixes both of these issues, by adding the relevant method, as well as updating the existing one to use the `X-Audit-Log-Reason` header, rather than the old query string method.

### CODE REVIEW

**Comment by mrbentarikau** [comment]
maybe prepend author also to RemoteTimeout function

**Comment by mrbentarikau** [comment]
now the same thing is in three places in the code, why not function it?

**Comment by Wolveric** [comment]
Where would you suggest putting it in that case?

**Comment by mrbentarikau** [comment]
into a function?

func fullReason(...
or whatever that name would be

**Comment by Wolveric** [comment]
I mean in the file, or file system...

**Comment by mrbentarikau** [comment]
to the bottom of punishemts.go for example : )

**Comment by mrbentarikau** [comment]
for example, I use > 
```go
// prepends author to action reason
func authorToReason(reason string, author *discordgo.User) (fullReason string) {
	fullReason = reason
	if author.ID != common.BotUser.ID {
		fullReason = author.String() + ": " + reason
	}
	return
}

**Pull request merged**
