### PR TITLE
removed words.

### PR DESCRIPTION
**Pull request by TokyoDownfall**
Turd, Jerk, Hell, Muff.

### CODE REVIEW

**Comment by ashishjh-bst** [comment]
Why are these being removed?

**Comment by ashishjh-bst** [comment]
Also, don't PR to master.

**Comment by TokyoDownfall** [comment]
Because I'm using it for my server
 However we do not need it anymore

**Comment by BlackWolfWoof** [comment]
> Because I'm using it for my server However we do not need it anymore
Well then use a custom list. Get the words from the default one, add them to your server and remove the ones you don't wanna have

**Comment by TokyoDownfall** [comment]
I apologize

**Pull request closed without merging**
