### PR TITLE
Trigger advanced automod rule if someone uses a slashcommand

### PR DESCRIPTION
**Pull request by Borbot33**
With this PR you can trigger an advanced automod rule via an interaction response. (If you execute a slashcommand)

### CODE REVIEW

**Comment by SoggySaussages** [comment]
I am struggling to understand what this PR does. 

I would greatly appreciate if you could embellish your PR comment significantly, as it seems you have included several incomplete sentences, and insufficient details to describe the changes. Is this a feature addition or a bug fix?

As an example, “It works same as before:” I am unclear what “it” is referring to, and what “it” did before this change. I cannot grasp what a “slashcommand message” or a “slashcommsnd webhook” are, let alone what “slashcommand messages support” in automod could mean or why it would be a necessary change. 

Finally, what is an “advanced automod tyle?”

**Comment by galen8183** [comment]
This removes webhook ID checks to let both automoderators also act on interaction response messages.
This *should* still ignore non-interaction webhooks, as the message author discriminator is `"0000"`.
I'm struggling to see the purpose of the addition of `MemberToMemberFields`, does `MemberStateFromMember` not have identical behaviour to what you've added here?

**Comment by galen8183** [comment]
> “slashcommand message” or a “slashcommsnd webhook”
Interaction responses I assume, since those are sent as webhook messages, all of which are currently ignored.

> "advanced automod tyle"
Looks like a typo of "advanced automod rule," however I think this would change both advanced and basic automod's behaviour equally.

**Comment by galen8183** [comment]
> I'm struggling to see the purpose of the addition of `MemberToMemberFields`, does `MemberStateFromMember` not have identical behaviour to what you've added here?

Ah, is this because [`bot.HandleMessageCreateUpdateFirst`](https://github.com/botlabs-gg/yagpdb/blob/9e59a6dc79554dde913d32bc66555b9e8a002b6f/bot/discordevents.go#L393) won't fill in the message member guild ID?
I wonder if this logic change would be more appropriate in `IsNormalUserMessage` directly, I haven't looked too hard if this would break something else though.

**Comment by SoggySaussages** [comment]
> > I'm struggling to see the purpose of the addition of `MemberToMemberFields`, does `MemberStateFromMember` not have identical behaviour to what you've added here?
> 
> Ah, is this because [`bot.HandleMessageCreateUpdateFirst`](https://github.com/botlabs-gg/yagpdb/blob/9e59a6dc79554dde913d32bc66555b9e8a002b6f/bot/discordevents.go#L393) won't fill in the message member GuildID, and subsequently the MemberState GuildID? I wonder if this logic change would be more appropriate in `IsNormalUserMessage` directly, I haven't looked too hard if this would break something else though.

This is an issue solved in other places in Yag code, such as [CC triggers](https://github.com/botlabs-gg/yagpdb/blob/master/customcommands/bot.go#L807), by manually setting the member’s guild ID after the variable is set. Should this convention be continued rather than adding on a whole new function?

**Comment by Borbot33** [comment]
> > > I'm struggling to see the purpose of the addition of `MemberToMemberFields`, does `MemberStateFromMember` not have identical behaviour to what you've added here?
> > 
> > 
> > Ah, is this because [`bot.HandleMessageCreateUpdateFirst`](https://github.com/botlabs-gg/yagpdb/blob/9e59a6dc79554dde913d32bc66555b9e8a002b6f/bot/discordevents.go#L393) won't fill in the message member GuildID, and subsequently the MemberState GuildID? I wonder if this logic change would be more appropriate in `IsNormalUserMessage` directly, I haven't looked too hard if this would break something else though.
> 
> This is an issue solved in other places in Yag code, such as [CC triggers](https://github.com/botlabs-gg/yagpdb/blob/master/customcommands/bot.go#L807), by manually setting the member’s guild ID after the variable is set. Should this convention be continued rather than adding on a whole new function?

Oh, my problem was the User 

> > I'm struggling to see the purpose of the addition of `MemberToMemberFields`, does `MemberStateFromMember` not have identical behaviour to what you've added here?
> 
> Ah, is this because [`bot.HandleMessageCreateUpdateFirst`](https://github.com/botlabs-gg/yagpdb/blob/9e59a6dc79554dde913d32bc66555b9e8a002b6f/bot/discordevents.go#L393) won't fill in the message member GuildID, and subsequently the MemberState GuildID? I wonder if this logic change would be more appropriate in `IsNormalUserMessage` directly, I haven't looked too hard if this would break something else though.

for me it was an issue with User and I didn't notice an issue with GuildID

**Comment by Borbot33** [comment]
> > > I'm struggling to see the purpose of the addition of `MemberToMemberFields`, does `MemberStateFromMember` not have identical behaviour to what you've added here?
> > 
> > 
> > Ah, is this because [`bot.HandleMessageCreateUpdateFirst`](https://github.com/botlabs-gg/yagpdb/blob/9e59a6dc79554dde913d32bc66555b9e8a002b6f/bot/discordevents.go#L393) won't fill in the message member GuildID, and subsequently the MemberState GuildID? I wonder if this logic change would be more appropriate in `IsNormalUserMessage` directly, I haven't looked too hard if this would break something else though.
> 
> This is an issue solved in other places in Yag code, such as [CC triggers](https://github.com/botlabs-gg/yagpdb/blob/master/customcommands/bot.go#L807), by manually setting the member’s guild ID after the variable is set. Should this convention be continued rather than adding on a whole new function?

I changed it, ty :)

**Comment by ashishjh-bst** [comment]
I am not sure what is the usecase for this?

**Comment by ashishjh-bst** [comment]
> > I am not sure what is the usecase for this?
> 
> You can delete messages that use slash commands, just like you could delete all bot messages before.

I understood that, but why is automod needed to be triggered on slash commands?

**Comment by Borbot33** [comment]
> > > I am not sure what is the usecase for this?
> > 
> > 
> > You can delete messages that use slash commands, just like you could delete all bot messages before.
> 
> I understood that, but why is automod needed to be triggered on slash commands?

Screenshot_20240715-144613
Hehe

**Comment by SoggySaussages** [comment]
> > > > I am not sure what is the usecase for this?
> > > 
> > > 
> > > You can delete messages that use slash commands, just like you could delete all bot messages before.
> > 
> > 
> > I understood that, but why is automod needed to be triggered on slash commands?
> 
> Screenshot_20240715-144613 Hehe

What does “Hehe” mean? A clear, articulable purpose for adding a feature is standard practice. Why have you not included one in full sentences, or even a full description of what the changes are in the first place? Why are you forcing us to extrapolate what this PR does and why it needs to exist?

**Comment by Borbot33** [comment]
> > > > > I am not sure what is the usecase for this?
> > > > 
> > > > 
> > > > You can delete messages that use slash commands, just like you could delete all bot messages before.
> > > 
> > > 
> > > I understood that, but why is automod needed to be triggered on slash commands?
> > 
> > 
> > Screenshot_20240715-144613 Hehe
> 
> What does “Hehe” mean? A clear, articulable purpose for adding a feature is standard practice. Why have you not included one in full sentences, or even a full description of what the changes are in the first place? Why are you forcing us to extrapolate what this PR does and why it needs to exist?

I thought that the description I gave was enough, but I didn't give any examples.

> You can delete messages that use slash commands, just like you could delete all bot messages before.

That was an usecase for me, but I closed the PR. Then I sent the screenshot of this message.

This PR is a lesson for me to be more professional and write better descriptions. (I hate this PR)
I'll close this PR and try to be better in the future.

I wish you a good day,
Borbot:3

**Pull request closed without merging**
