### PR TITLE
Added annoying and cocky

### PR DESCRIPTION
**Pull request by User9684**
Yes, I put them in correct position for alphabetical order

### CODE REVIEW

**Comment by BlackWolfWoof** [comment]
Add furry too *troll*

**Comment by ashishjh-bst** [comment]
@BlackWolfWoof  ;gopr

**Comment by BlackWolfWoof** [comment]
> @BlackWolfWoof  ;gopr

If you dare me i will do it

**Comment by ashishjh-bst** [comment]
@BlackWolfWoof  I double dare you.

**Comment by BlackWolfWoof** [comment]
Ok, noted :3
Gonna do when I come home.
I might add words like fluffy, soft, fuzzy, furry if they don't exist already hehe.
**Also nobody can stop me muhahah** *other than you des*

**Pull request merged**
