### PR TITLE
module: fix go version

### PR DESCRIPTION
**Pull request by SoggySaussages**
This solves an issue with go build attempting to automatically update go to a version that doesn’t technically exist.

Signed-off-by: SoggySaussages <vmdmaharaj@gmail.com>

### CODE REVIEW

**Comment by ashishjh-bst** [comment]
I have never had this issue, can you add steps for me to reproduce this issues please?

**Comment by SoggySaussages** [comment]
I encountered on Ubuntu Server 20.04 whilst running standalone, if I try to build without the `.0` appended it doesn’t work. Even after running with the `.0` appended and then subsequently removing it again, same issue.

```
***@***.***:~/sgpdb/cmd/sgpdb$ sh build.sh
Building version SGPDBv1.6.0-44-g6ecc4c5b
go: downloading go1.23 (linux/amd64)
go: download go1.23 for linux/amd64: toolchain not available
```

**Comment by galen8183** [comment]
Apparently excluding the minor version indicates a development version only: https://github.com/golang/go/issues/62278#issuecomment-1693538776

**Comment by ashishjh-bst** [comment]
in that case it should point to the latest version, which at this point is 1.23.3

**Comment by SoggySaussages** [comment]
Donezo

**Pull request merged**
