### PR TITLE
Update help error message

### PR DESCRIPTION
**Pull request by Max-Almighty**
This is a command that is used quite often, and people can get confused with the "bot blocked" part in the error, as simple having your direct messages closed also prompts the same error. Just adding the "DMs closed" to the error could make things better

### CODE REVIEW

**Comment by l-zeuch** [comment]
Don't PR to master >
> If you want to make a contribution, create a fork, cut a branch from master, make the necessary changes and then make a PR to the dev branch (botlabs-gg/yagpdb/dev). This is key for larger commits and edits to important / complicated parts of the bot so it can be tested safely without breaking everything.

**Comment by Max-Almighty** [comment]
Ah, sorry about that

**Comment by l-zeuch** [comment]
Just edit the PR to have a different base branch, top right.

**Comment by l-zeuch** [comment]
Looks like some unrelated changes trickled into this PR?
image

**Comment by Max-Almighty** [comment]
Wait I meant that for a new PR

**Comment by Max-Almighty** [comment]
How would I delete that commit?

**Comment by ashishjh-bst** [comment]
> 

`git reset --hard b8a1607f67d4b45959c806908c6c355394c55099`

**Comment by l-zeuch** [comment]
> How would I delete that commit?

`git reset --hard b8a1607 && git push --force-with-lease`
on your feature branch

**Pull request merged**
