### PR TITLE
Switch to custom library & fix bug where it would check sanitized content even when disabled

### PR DESCRIPTION
**Pull request by User9684**

### CODE REVIEW

**Comment by User9684** [comment]
WHY DID IT NOT SQUASH

**Comment by User9684** [comment]
For people who wanna add confusables that aren't defined by unicode, add them into the "extraConfusables.json" file and run "go generate"

**Comment by ashishjh-bst** [comment]
This needs rebasing, and there are conflicts that need to be resolved. 
Dockerfile has changes that shouldn't be in this PR.

**Comment by User9684** [comment]
> This needs rebasing, and there are conflicts that need to be resolved. Dockerfile has changes that shouldn't be in this PR.

oh shit I forgot to exclude the dockerfile change

**Comment by User9684** [comment]
Too many mess-ups in this PR, I'm just gonna remake it lol

**Pull request closed without merging**
