### PR TITLE
idk, random things to add into throw

### PR DESCRIPTION
**Pull request by User9684**

### CODE REVIEW

**Comment by mrbentarikau** [comment]
idk, maybe test your code before posting?

**Comment by User9684** [comment]
wdym?

**Comment by User9684** [comment]
does golang require you to have a , at the end of arrays or something?

**Comment by User9684** [comment]
added one at the end just in case because i have no clue, kinda new to golang ok

**Comment by User9684** [comment]
> idk, maybe test your code before posting?

not very constructive

**Comment by mrbentarikau** [comment]
kindergarten-speech on Github is also not very constructive. Pullrequesting broken, not tested code is not very good idea...

**Comment by User9684** [comment]
> Pullrequesting broken
? Don't understand what this is supposed to mean
> not tested code is not very good idea
Kinda hard to test when you are just given "name must be main" on playground 🤷

**Pull request closed without merging**
