### PR TITLE
Fancy Error Message

### PR DESCRIPTION
**Pull request by Shadow21AR**
Intead of giving link to that site, we give fancy error in embed :>

### CODE REVIEW

**Comment by mrbentarikau** [comment]
This is not #general channel of YAGPDB Discord community... start wording your PRs better.  Title `Fancy Error Message`  tells nothing, means nothing.

**Comment by ashishjh-bst** [comment]
Please elaborate on the changes done, and attach screenshot of the error message.

**Comment by Shadow21AR** [comment]
instead of giving link to list of codes like this (old)
image

New changes made to show list in embed , 15 of them at a time (new)
image

**Comment by jo3-l** [comment]
Driveby comment: the old message makes it clear that an invalid currency code was provided; the new one, not so much.

**Pull request closed without merging**
