### PR TITLE
Update swearwords.go

### PR DESCRIPTION
**Pull request by sudheer0071**

### CODE REVIEW

**Comment by sudheer0071** [comment]
please add these words

**Comment by l-zeuch** [comment]
Use your own list in Basic Automod, and don't PR to `master`.

**Review by sudheer0071 — COMMENTED** [review]
Please add these words

**Comment by sudheer0071** [comment]
> Use your own list in Basic Automod, and don't PR to `master`.

okk

**Comment by mrbentarikau** [comment]
use other tools YAG has for building custom swearword filters, e.g. `mc` is definitely not a swearword. In mc context MineCraft is and Midnight Commander or Master of Ceremony are not : )

**Comment by ashishjh-bst** [comment]
We do not support regional slurs and swearwords in the default list, as others have recommended use the custom list option available in yagpdb, or selfhost. 

Please read the Contributing guidelines next time before raising a PR.

**Pull request closed without merging**
